image: Visual Studio 2022

artifacts:
  - path: '**\*.nupkg'

configuration:
  - Release

before_build:
  - cmd: dotnet restore interactive-extensions.sln

build_script:
  - cmd: >-
      dotnet build interactive-extensions.sln /p:VersionPrefix=%APPVEYOR_BUILD_VERSION%

after_build:
  - cmd: >-
      dotnet pack .\src\Ollama.Interactive\Ollama.Interactive.csproj --no-build /p:VersionPrefix=%APPVEYOR_BUILD_VERSION%

test_script:
  - cmd: dotnet test .\src\Ollama.Interactive.Tests\Ollama.Interactive.Tests.csproj
